import { RiftRelayGame } from './rift-game.mjs';

const RIFT_ID = 'rift-relay';
const MAX_SCORE = 999999;
const translations = {
  en: { appName:'Social Challenge Arena',effects:'Effects',eyebrow:'Endless social skill run',hero:'Move. Read. Decide. Survive.',intro:'A different route every run. Share one seed and challenge a friend on the exact same course.',flagship:'Flagship challenge',name:'Rift Relay',tagline:'Three lanes, shifting rules, endless pressure.',play:'Play',instructionTitle:'Read the route before it reaches you.',howTo:'Move between three lanes, jump gaps, avoid blocked gates, and solve signal rules. The run ends when all chances are lost or you exit.',start:'Start run',back:'Back',score:'Score',zone:'Zone',lives:'Chances',streak:'Streak',exit:'Exit',result:'Your result',share:'Challenge a friend',replay:'Replay',newRoute:'New route',home:'Home',riftClear:'Route cleared +{points}',riftHit:'Route missed',finished:'Run ended with {score}',target:'Beat {score} on the same route',win:'You won by {value}',lose:'You need {value} more',tie:'Exact tie',copied:'Challenge link copied',sharePrompt:'Copy this challenge link'},
  ar: { appName:'ساحة التحديات الاجتماعية',effects:'المؤثرات',eyebrow:'تحدٍ اجتماعي لا نهائي',hero:'تحرّك. اقرأ. قرّر. واصل.',intro:'مسار مختلف في كل محاولة. شارك البذرة نفسها وتحدَّ صديقك على المسار المطابق.',flagship:'التحدي الرئيسي',name:'سباق الشقوق',tagline:'ثلاثة مسارات وقواعد متغيرة وضغط متصاعد.',play:'العب',instructionTitle:'اقرأ المسار قبل أن يصل إليك.',howTo:'انتقل بين ثلاثة مسارات، واقفز فوق الفجوات، وتجنب البوابات المحظورة، وحل قواعد الإشارات. تنتهي المحاولة عند نفاد الفرص أو الخروج.',start:'ابدأ المحاولة',back:'رجوع',score:'النتيجة',zone:'المنطقة',lives:'الفرص',streak:'التتابع',exit:'خروج',result:'نتيجتك',share:'تحدَّ صديقًا',replay:'إعادة',newRoute:'مسار جديد',home:'الرئيسية',riftClear:'تم اجتياز المسار +{points}',riftHit:'أخفقت في المسار',finished:'انتهت المحاولة بنتيجة {score}',target:'تجاوز {score} على المسار نفسه',win:'فزت بفارق {value}',lose:'تحتاج {value} إضافية',tie:'تعادل تام',copied:'تم نسخ رابط التحدي',sharePrompt:'انسخ رابط التحدي'},
  tr: { appName:'Sosyal Meydan Okuma Arenası',effects:'Efektler',eyebrow:'Sonsuz sosyal beceri koşusu',hero:'Hareket et. Oku. Karar ver. Dayan.',intro:'Her koşuda farklı bir rota. Aynı tohumu paylaş ve arkadaşınla aynı parkurda yarış.',flagship:'Ana meydan okuma',name:'Rift Relay',tagline:'Üç şerit, değişen kurallar, artan baskı.',play:'Oyna',instructionTitle:'Rota sana ulaşmadan onu oku.',howTo:'Üç şerit arasında hareket et, boşlukların üzerinden atla, kapalı geçitlerden kaçın ve sinyal kurallarını çöz. Hakların bittiğinde veya çıktığında koşu sona erer.',start:'Koşuyu başlat',back:'Geri',score:'Puan',zone:'Bölge',lives:'Hak',streak:'Seri',exit:'Çık',result:'Sonucun',share:'Arkadaşına meydan oku',replay:'Tekrar',newRoute:'Yeni rota',home:'Ana sayfa',riftClear:'Rota geçildi +{points}',riftHit:'Rota kaçırıldı',finished:'Koşu {score} puanla bitti',target:'Aynı rotada {score} puanı geç',win:'{value} farkla kazandın',lose:'{value} puan daha gerekli',tie:'Tam beraberlik',copied:'Meydan okuma bağlantısı kopyalandı',sharePrompt:'Bu bağlantıyı kopyala'}
};

function normalizeLanguage(value){const short=String(value||'en').toLowerCase().split('-')[0];return translations[short]?short:'en'}
function randomSeed(){return Math.floor(Math.random()*0x100000000)>>>0}
function safeNumber(value,max=MAX_SCORE){const number=Number(value);return Number.isInteger(number)&&number>=0&&number<=max?number:null}
function copy(key,values={}){let text=translations[state.language][key]??translations.en[key]??key;for(const [name,value] of Object.entries(values))text=text.replaceAll(`{${name}}`,String(value));return text}
function parseInvite(){const params=new URLSearchParams(location.search);if(!params.has('c')&&!params.has('s')&&!params.has('t'))return null;if(params.get('c')!==RIFT_ID)return null;const seed=safeNumber(params.get('s'),0xffffffff);const target=safeNumber(params.get('t'));if(seed===null||target===null)return null;return{seed,target}}
function inviteUrl(score){const url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('c',RIFT_ID);url.searchParams.set('s',String(state.seed));url.searchParams.set('t',String(Math.min(MAX_SCORE,score)));return url.toString()}

const state={language:normalizeLanguage(localStorage.getItem('sca-language')||navigator.language),reducedMotion:localStorage.getItem('sca-reduced-motion')==='true'||matchMedia('(prefers-reduced-motion: reduce)').matches,screen:'discovery',seed:randomSeed(),invite:parseInvite(),result:null};
if(state.invite)state.seed=state.invite.seed;
let game=null;
const $=(selector)=>document.querySelector(selector);
const elements={language:$('#language-select'),motion:$('#motion-toggle'),open:$('#open-button'),start:$('#start-button'),back:$('#back-button'),arena:$('#rift-arena'),score:$('#score-value'),zone:$('#zone-value'),lives:$('#lives-value'),combo:$('#combo-value'),status:$('#game-status'),target:$('#invite-target'),resultScore:$('#result-score'),resultSummary:$('#result-summary'),comparison:$('#comparison'),share:$('#share-button'),replay:$('#replay-button'),newRoute:$('#new-button'),home:$('#home-button')};

function applyLanguage(){document.documentElement.lang=state.language;document.documentElement.dir=state.language==='ar'?'rtl':'ltr';document.title=copy('appName');elements.language.value=state.language;elements.motion.setAttribute('aria-pressed',String(state.reducedMotion));document.querySelectorAll('[data-copy]').forEach((element)=>{element.textContent=copy(element.dataset.copy)});elements.target.hidden=!state.invite;elements.target.textContent=state.invite?copy('target',{score:state.invite.target}):'';if(state.result)renderResult()}
function setScreen(screen){state.screen=screen;document.querySelectorAll('[data-screen]').forEach((section)=>{section.hidden=section.dataset.screen!==screen});if(screen!=='game'&&game){game.destroy();game=null}document.querySelector(`[data-screen="${screen}"] h1,[data-screen="${screen}"] h2, [data-screen="${screen}"] button`)?.focus({preventScroll:true})}
function announce(event){const message=copy(event.key,event.values);elements.status.textContent='';requestAnimationFrame(()=>{elements.status.textContent=message})}
function updateHud(snapshot){elements.score.textContent=String(snapshot.score);elements.zone.textContent=String((snapshot.round??0)+1);elements.lives.textContent=String(snapshot.lives);elements.combo.textContent=String(snapshot.combo)}
function beginRun(){state.result=null;updateHud({score:0,round:0,lives:3,combo:0});setScreen('game');game=new RiftRelayGame({container:elements.arena,reducedMotion:state.reducedMotion,onUpdate:updateHud,onAnnounce:announce,onFinish:(result)=>{state.result=result;renderResult();setScreen('result')}});game.start(state.seed)}
function comparisonText(){if(!state.invite||!state.result)return'';const difference=state.result.score-state.invite.target;if(difference>0)return copy('win',{value:difference});if(difference<0)return copy('lose',{value:Math.abs(difference)});return copy('tie')}
function renderResult(){if(!state.result)return;elements.resultScore.textContent=String(state.result.score);elements.resultSummary.textContent=copy('finished',{score:state.result.score});elements.comparison.hidden=!state.invite;elements.comparison.textContent=comparisonText()}
async function share(){if(!state.result)return;const url=inviteUrl(state.result.score);const data={title:copy('name'),text:`${copy('name')}: ${state.result.score}`,url};try{if(navigator.share){await navigator.share(data);return}await navigator.clipboard.writeText(url);elements.status.textContent=copy('copied')}catch{window.prompt(copy('sharePrompt'),url)}}

state.invite&&setScreen('instructions');
elements.open.addEventListener('click',()=>setScreen('instructions'));
elements.start.addEventListener('click',beginRun);
elements.back.addEventListener('click',()=>{history.replaceState({},'',location.pathname);state.invite=null;setScreen('discovery')});
elements.replay.addEventListener('click',beginRun);
elements.newRoute.addEventListener('click',()=>{state.invite=null;state.seed=randomSeed();history.replaceState({},'',location.pathname);beginRun()});
elements.home.addEventListener('click',()=>{state.invite=null;history.replaceState({},'',location.pathname);setScreen('discovery')});
elements.share.addEventListener('click',share);
elements.language.addEventListener('change',()=>{state.language=normalizeLanguage(elements.language.value);localStorage.setItem('sca-language',state.language);applyLanguage()});
elements.motion.addEventListener('click',()=>{state.reducedMotion=!state.reducedMotion;localStorage.setItem('sca-reduced-motion',String(state.reducedMotion));applyLanguage()});
applyLanguage();
