import{generateRiftZone,scoreRiftAction}from'./rift-relay-model.mjs';
const SWIPE=32;
export class RiftRelayGame{
constructor({container,reducedMotion=false,onUpdate=()=>{},onAnnounce=()=>{},onFinish=()=>{}}){this.container=container;this.canvas=container.querySelector('canvas');this.ctx=this.canvas.getContext('2d');this.reducedMotion=reducedMotion;this.onUpdate=onUpdate;this.onAnnounce=onAnnounce;this.onFinish=onFinish;this.abort=new AbortController();this.running=false;this.score=0;this.combo=0;this.lives=3;this.zoneNumber=0;this.eventIndex=0;this.track=0;this.jumpStart=0;this.slideUntil=0;this.progress=0;this.pointer=null;this.particles=[];this.shake=0;this.world=0}
start(seed){this.seed=Number(seed)>>>0;this.running=true;this.bind();this.resize();this.loadEvent();this.lastTime=performance.now();this.frame=requestAnimationFrame(t=>this.tick(t));this.container.focus({preventScroll:true})}
bind(){const s=this.abort.signal;this.container.querySelector('[data-rift-exit]')?.addEventListener('click',e=>{e.stopPropagation();this.finish('ended')},{signal:s});this.container.addEventListener('pointerdown',e=>{if(e.target.closest('[data-rift-exit]'))return;this.pointer={id:e.pointerId,x:e.clientX,y:e.clientY};this.container.setPointerCapture?.(e.pointerId);e.preventDefault()},{signal:s});this.container.addEventListener('pointerup',e=>{if(!this.pointer||this.pointer.id!==e.pointerId)return;const dx=e.clientX-this.pointer.x,dy=e.clientY-this.pointer.y;this.pointer=null;if(Math.abs(dy)>SWIPE&&Math.abs(dy)>Math.abs(dx)){if(dy<0)this.switchTrack(1);else this.slide()}else this.jump();e.preventDefault()},{signal:s});this.container.addEventListener('pointercancel',()=>this.pointer=null,{signal:s});this.container.addEventListener('contextmenu',e=>e.preventDefault(),{signal:s});this.container.addEventListener('keydown',e=>{if(e.key==='ArrowUp')this.switchTrack(1);if(e.key==='ArrowDown')this.slide();if(e.code==='Space')this.jump();if(e.key==='Escape')this.finish('ended');e.preventDefault()},{signal:s});addEventListener('resize',()=>this.resize(),{signal:s})}
resize(){const r=this.canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);this.canvas.width=Math.max(320,Math.round(r.width*d));this.canvas.height=Math.max(360,Math.round(r.height*d));this.ctx.setTransform(d,0,0,d,0,0);this.w=r.width;this.h=r.height}
currentZone(){return generateRiftZone(this.seed,this.zoneNumber)}
loadEvent(){const z=this.currentZone();if(this.eventIndex>=z.events.length){if(z.difficulty.recovery&&this.lives<3)this.lives++;this.zoneNumber++;this.eventIndex=0;return this.loadEvent()}this.active=z.events[this.eventIndex];this.progress=0;this.container.dataset.biome=z.biome;this.container.dataset.stage=z.stage;this.container.querySelector('[data-rift-zone]').textContent=`${z.biome} · ${this.zoneNumber+1}`;this.container.querySelector('[data-rift-rule]').textContent=this.ruleText();this.onUpdate({score:this.score,round:this.zoneNumber,lives:this.lives,combo:this.combo})}
ruleText(){const a=this.active;if(a.type!=='gate')return a.requiresSlide?'SWIPE DOWN TO SLIDE':a.requiresJump?'TAP TO JUMP':'READ THE PATH';return({match:'MATCH THE SYMBOL',direction:'FOLLOW THE ARROW',count:'CHOOSE THE COUNT',invert:'CHOOSE THE OPPOSITE',memory:'REMEMBER THE PULSE',transform:'ROTATE THEN CHOOSE'})[a.rule.family]||'SOLVE THE GATE'}
switchTrack(up){this.track=up?1:0;this.spark('#76e8ff')}
jump(){const now=performance.now();if(now-this.jumpStart<360)return;this.jumpStart=now;this.spark('#ffe46b')}
slide(){this.track=0;this.slideUntil=performance.now()+650;this.spark('#8ff0c2')}
playerY(){return this.track?this.h*.45:this.h*.72}
tick(t){if(!this.running)return;const dt=Math.min(40,t-this.lastTime||16);this.lastTime=t;const z=this.currentZone();this.world+=dt*z.difficulty.speed*.22;this.progress+=dt/(z.difficulty.windowMs/z.difficulty.speed);if(this.progress>=1)this.resolve(t);this.draw(t,z);this.frame=requestAnimationFrame(n=>this.tick(n))}
resolve(t){const a=this.active,jumping=t-this.jumpStart<620,sliding=t<this.slideUntil;let ok=true;if(a.type==='gate')ok=this.track===a.rule.correctTrack;else{if(this.track!==a.track&&a.type!=='drone')ok=false;if(a.requiresJump&&!jumping)ok=false;if(a.requiresSlide&&!sliding)ok=false}if(ok){this.combo++;const pts=scoreRiftAction({distance:this.zoneNumber*10+this.eventIndex,streak:this.combo,risk:a.risk,puzzle:a.type==='gate',stage:this.zoneNumber%7});this.score+=pts;this.spark('#71f0b1',20);this.onAnnounce({key:'riftClear',values:{points:pts}})}else{this.lives--;this.combo=0;this.shake=11;this.spark('#ff637d',24);this.onAnnounce({key:'riftHit',values:{}})}this.eventIndex++;this.onUpdate({score:this.score,round:this.zoneNumber,lives:this.lives,combo:this.combo});if(this.lives<=0)return this.finish('failed');this.loadEvent()}
spark(color,n=10){for(let i=0;i<n;i++)this.particles.push({x:this.w*.24,y:this.playerY(),vx:(Math.random()-.5)*6,vy:(Math.random()-.6)*6,a:1,color})}
draw(t,z){const c=this.ctx,w=this.w,h=this.h;c.save();if(this.shake&&!this.reducedMotion){c.translate((Math.random()-.5)*this.shake,(Math.random()-.5)*this.shake);this.shake*=.8}const palettes={meadow:['#7ed6ff','#2f9b68','#f7d86f'],foundry:['#5a2431','#bc5038','#ffb15d'],cloud:['#8ad9ff','#537ad8','#ffffff'],vault:['#261b47','#6848a8','#e3c9ff'],storm:['#191d3b','#6d3d8e','#ff6886'],core:['#102b3a','#1c8c8c','#ffe56d'],garden:['#89d8c2','#3d8d68','#f5efb7']};const p=palettes[z.biome]||palettes.meadow;let g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,p[0]);g.addColorStop(.58,p[1]);g.addColorStop(1,'#102018');c.fillStyle=g;c.fillRect(0,0,w,h);for(let layer=0;layer<3;layer++){c.fillStyle=layer===0?'#ffffff20':layer===1?'#17344b66':'#0e2435aa';c.beginPath();c.moveTo(0,h*(.5+layer*.08));for(let x=0;x<=w+80;x+=80){const y=h*(.48+layer*.09)+Math.sin((x+this.world*(layer+1)*.45)/90)*30;c.lineTo(x,y)}c.lineTo(w,h);c.lineTo(0,h);c.fill()}const lower=h*.78,upper=h*.51;for(const y of[upper,lower]){c.fillStyle=z.biome==='foundry'?'#372323':'#213f35';c.fillRect(0,y+25,w,h-y);c.fillStyle=p[2];for(let x=-60;x<w+60;x+=46)c.fillRect(((x-this.world*.8)%(w+120)),y+20,36,7)}const ex=w*.88-this.progress*w*.72,ey=this.active.type==='gate'?(this.active.rule.correctTrack?upper:lower):(this.active.track?upper:lower);this.drawEvent(c,ex,ey);const py=this.playerY(),jump=t-this.jumpStart<620?Math.sin((t-this.jumpStart)/620*Math.PI)*72:0,slide=t<this.slideUntil;c.save();c.translate(w*.24,py-jump);if(slide)c.scale(1.25,.58);c.fillStyle='#f7fbff';c.strokeStyle='#13202d';c.lineWidth=4;c.beginPath();c.arc(0,-18,15,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#174a6a';c.fillRect(-14,-4,28,34);c.fillStyle=p[2];c.fillRect(8,4,20,7);c.fillStyle='#10202c';c.fillRect(-12,30,10,16);c.fillRect(5,30,10,16);c.restore();this.particles=this.particles.filter(q=>q.a>.03);for(const q of this.particles){q.x+=q.vx;q.y+=q.vy;q.vy+=.2;q.a*=.92;c.globalAlpha=q.a;c.fillStyle=q.color;c.fillRect(q.x,q.y,5,5)}c.globalAlpha=1;c.fillStyle='#fff';c.font='900 12px system-ui';c.fillText(z.stage.toUpperCase(),12,h-14);c.restore()}
drawEvent(c,x,y){const a=this.active;c.save();c.translate(x,y);const s=.65+this.progress*.45;c.scale(s,s);if(a.type==='gate'){for(const track of[0,1]){const yy=track===1?-70:5;c.fillStyle=track===a.rule.correctTrack?'#ffe36b':'#ff617a';c.strokeStyle='#13202d';c.lineWidth=5;c.beginPath();c.roundRect(-38,yy-36,76,72,15);c.fill();c.stroke();c.fillStyle='#13202d';c.font='bold 28px system-ui';c.textAlign='center';c.fillText(['◆','▲','●','■'][(a.rule.cue+track)%4],0,yy+9)}}else{c.fillStyle=a.type==='gap'?'#08121c':a.type==='rock'?'#6b4d35':a.type==='arch'?'#c98a52':a.type==='crusher'?'#ff6b58':'#e7d36c';c.strokeStyle='#13202d';c.lineWidth=5;if(a.type==='gap')c.fillRect(-42,10,84,18);else if(a.requiresSlide)c.fillRect(-45,-55,90,24);else{c.beginPath();c.roundRect(-32,-48,64,76,12);c.fill();c.stroke()}}c.restore()}
finish(reason){if(!this.running)return;this.running=false;cancelAnimationFrame(this.frame);this.onFinish({score:this.score,reason,round:this.zoneNumber,combo:this.combo})}
destroy(){this.running=false;cancelAnimationFrame(this.frame);this.abort.abort()}}
